const ADD_POSTS = 'ADD_POSTS'
const ADD_POST = 'ADD_POST'
const UPDATE_POST = 'UPDATE_POST'
const UPDATE_COMMENT = 'UPDATE_POST'
const ADD_COMMENT = 'ADD_COMMENT'
const ADD_COMMENTS = 'ADD_COMMENTS'

export {ADD_POSTS, ADD_POST, UPDATE_POST, ADD_COMMENT, ADD_COMMENTS, UPDATE_COMMENT};